### ISSUE TITLE
Specify User Agent

### ISSUE THREAD

**Issue by BiviaBen** [Bmcgarry194/chessvision#1]
Hi, there. I'm Ben, from Chess.com. This is a great piece of software you built! We first noticed it in our logs and at the time it uncovered some problems in our caching and we debated if we needed to temporarily block the software while we fixed things. Everything is good now — but we would love contact info!

Take a note of this in the API docs:
> In some cases, if we detect abnormal or suspicious activity, we may block your application entirely. If you supply a recognizable user-agent that contains contact information, then if we must block you application we will attempt to contact you to correct the problem.

The best way to help us provide a better API is for you to customize your user-agent string to reflect what the application is and does, plus valid contact information so we can reach you if needed.

Please let us know if this is possible, and keep you the amazing work!

**Comment by Bmcgarry194** [comment]
Hi Ben, thanks for taking a look at my work! I just added in a user-agent header to my requests, so that should do it. Let me know if thats what you were thinking, and thanks for the great api to work with!

**Comment by BiviaBen** [comment]
That looks great! We see in our logs a few dozen hits with this user-agent, probably when you were testing. We still have a single IP address hitting the game archives endpoints like ChessVision does, but with the user-agent "Python-urllib/3.5". I assume this is just some older code out there?
